# config/packages/easy_admin.yaml
easy_admin:
    formats:
        date:     'd/m/Y'           # Format d'affichage des dates
        time:     'H:i:s'           # Format d'affichage des heures/minutes/secondes
        datetime: 'd/m/Y H:i:s'     # Format d'affichage des datetime
    site_name: 'Administration Générale'    # Nom du backoffice, marqué en haut à gauche de l'interface
    design:
        form_theme:
            - "@EasyAdmin/form/bootstrap_4.html.twig"           # Active le thème de bootstrap 4 pour l'apparence des formulaires
            - "@FOSCKEditor/Form/ckeditor_widget.html.twig"     # Active le thème de ckeditor pour les champs ckeditor
        brand_color: 'black'        # Couleur principale du backoffice (boutons, icônes, etc...)
        menu:       # Paramétrage du menu de gauche
            - { label: 'Revenir au site', route: 'accueil', icon: 'link'}     # Création d'un lien permettant de revenir sur le site sur l'accueil
            - User      # Affiche le menu principal pour l'entité "User" (on pourrait en mettre d'autres pour d'autres entités du site)
            - Opinion
    entities:       # Paramétrage de la gestion des entités du site par easyadmin
        User:       # Paramétrage de l'entité User
            class: App\Entity\User      # Classe de l'entité User
            label: 'Utilisateurs'       # Nom d'affichage de l'entité User
            list:       # Paramétrage de l'onglet d'affichage des utilisateurs
                title: 'Liste des utilisateurs'     # Titre de l'onglet
                sort: ['id', 'ASC']     # Tri par défaut
                fields:     # Paramétrage des colonnes affichées ainsi que de leur type et leur titre
                    - {property: 'id', label: 'ID'}
                    - {property: 'firstname', label: 'Prénom'}
                    - {property: 'lastname', label: 'Nom de famille'}
                    - {property: 'email', type: 'email', label: 'Adresse Email'}
                    - {property: 'verified', label: 'Email confirmé'}
            edit:   # Paramétrage de l'onglet de modification d'un utilisateur
                title: 'Modifier un utilisateur'    # Titre de l'onglet
                fields:     # Paramétrage des champs qui seront affichés dans le formulaire d'édition, ainsi que leur type et leur label
                    - {property: 'email', type: 'email', label: 'Adresse Email'}
                    - {property: 'firstname', label: 'Prénom'}
                    - {property: 'lastname', label: 'Nom de famille'}
                    - {property: 'verified', label: 'Email confirmé'}
        Opinion:
            class: App\Entity\Opinion
            label: 'Avis'
            list:
                title: 'Liste des avis'
                sort: ['publicationDate', DESC]
                fields:
                    - {property: 'id', label: 'ID'}
                    - {property: 'author', label: 'Auteur'}
                    - {property: 'title', label: 'Titre'}
                    - {property: 'mark' , label: 'Note'}
                    - {property: 'content', label: 'Contenu'}
                    - {property: 'publicationDate', label: 'Date'}
